#!/bin/bash

source utils.lib

function main {
    init

    if [ ! -e $vmlinux ]; then
	die "Cannot find $vmlinux"
    fi

    addr=$(nm $vmlinux | grep " ${sym}$" | awk '{print $1}')
    if [ -z $addr ]; then
	die "Cannot find sym:$sym in $vmlinux"
    fi

    echo $(addr2line -e $vmlinux $addr)
    exit 0
}

sym=$1
main
