#!/bin/bash

source utils.lib

function main {
    init

    [ -e "${vmlinux}" ] || die "Cannot find $vmlinux"

    addr=$(nm "${vmlinux}" | grep " ${sym}$" | awk '{print $1}')
    [ $addr ] || "Cannot find sym:${sym} in ${vmlinux}"

    echo $(addr2line -e "${vmlinux}" "${addr}")
    exit 0
}

sym="$1"
main
