#!/bin/bash

source utils.lib
exec="/usr/bin/synclient"

function usage {
    die "Usage: $(basename $0) [on/off]"
}

function check_exec {
    [ -e "${exec}" ] || die "Cannot find ${exec}"
}

function touchpad_on {
    $exec TouchpadOff=0
}

function touchpad_off {
    $exec TouchpadOff=1
}

function touchpad_list {
    $exec -l | grep TouchpadOff
}

function main {
    check_exec

    case "${cmd}" in
	"on")
	    touchpad_on
	    ;;
	"off")
	    touchpad_off
	    ;;
	"list")
	    touchpad_list
	    ;;
	*)
	    usage
	    ;;
    esac
    exit 0
}

if [ $# = '1' ]; then
    cmd="$1"
else
    cmd="list"
fi

main
