#!/usr/bin/env python

import sys
import os
import subprocess
import collections

#              alias     real              host   port
alias_list = [('hm1'   , 'hm1'           , 'hm1', '22'),
              ('hm2'   , 'hm2'           , 'hm2', '22'),
              ('hg1'   , 'hg1'           , 'hg1', '22'),
              ('hg2'   , 'hg2'           , 'hg2', '22'),

              ('vmx'   , 'hm1-1-vmx'     , 'hm1', '22'),
              ('bzr'   , 'hm1-2-vbzr'    , 'hm1', '22'),
              ('vqa'   , 'hm1-3-vqa'     , 'hm1', '22'),
              ('v10000', 'hm1-4-v10000'  , 'hm1', '22'),
              ('vmp'   , 'hm1-5-vmp'     , 'hm1', '22'),
              ('vwwqa' , 'hm1-6-vwwqa'   , 'hm1', '22'),
              ('debqa' , 'hm1-7-vdebqa'  , 'hm1', '22'),
              ('ldap'  , 'hm1-8-vldap'   , 'hm1', '22'),
              ('debu1' , 'hm1-9-vdebu1'  , 'hm1', '22'),

              ('dev'   , 'hm2-1-vdev'    , 'hm2', '22'),

              ('puppet', 'hg1-1-vpuppet' , 'hg1', '22'),
              ('10018b', 'hg1-2-v10018b' , 'hg1', '22'),
              ('10103' , 'hg1-3-v10103'  , 'hg1', '22'),
              ('10104' , 'hg1-4-v10104'  , 'hg1', '22'),
              ('10105' , 'hg1-5-v10105'  , 'hg1', '22'),
              ('10106' , 'hg1-6-v10106'  , 'hg1', '22'),
              ('10107' , 'hg1-7-v10107'  , 'hg1', '22'),

              ('boss'  , 'hg2-1-v10101'  , 'hg2', '22'),
              ('demo'  , 'hg2-2-vdemo'   , 'hg2', '22'),
              ('www'   , 'hg2-3-vwww'    , 'hg2', '22'),
              ('boden' , 'hg2-4-boden'   , 'hg2', '22'),
              ('matrix', 'hg2-5-vmatrix' , 'hg2', '22'),
              ('flash' , 'hg2-7-vflash'  , 'hg2', '22'),
              ('sbr'   , 'hg2-8-vsbr'    , 'hg2', '22'),
              ('10070' , 'hg2-9-v10070'  , 'hg2', '22'),
              ('10063b', 'hg2-10-v10063b', 'hg2', '22'),
              ('ngibi' , 'hg2-11-vngibi' , 'hg2', '22'),
              ('10083b', 'hg2-12-v10083b', 'hg2', '22'),
              ('10018b', 'hg2-13-v10018b', 'hg2', '22'),

              ('gray', 'mail.graystone.com.au', 'mail.graystone.com.au', '22208'),
              ]


class auto_dict(dict):
    def __getitem__(self, key):
        try:
            return dict.__getitem__(self, key)
        except KeyError:
            value = self[key] = type(self)()
            return value

class Alias:
    def __init__(self, a_list):
        self.alias = auto_dict()
        for a in a_list:
            self.alias[a[0]]['real'] = a[1]
            self.alias[a[0]]['host'] = a[2]
            self.alias[a[0]]['port'] = a[3]

    def __getitem__(self, key):
        item = self.alias[key]
        if item == {}:
            raise KeyError
        return item

def ls_host(host, port, user):
    subprocess.call(['virsh', '-c', 'qemu+ssh://' + user + '@' + host + ':' + port + '/system', 'list --all'])

def go_host(host, port, user):
    subprocess.call(['virsh', '-c', 'qemu+ssh://' + user + '@' + host + ':' + port + '/system'])

def view_real(host, port, real, user):
    subprocess.call(['virt-viewer', '-c', 'qemu+ssh://' + user + '@' + host + ':' + port + '/system', real])

def ssh_target(target, port, user):
    subprocess.call(['ssh', '-X', '-p', port, user + '@' + target])

def usage(prog):
    print 'usage:', prog, '<command> <args ...>'
    print '''The commands support are:
    ls      List kvm virtual on a kvm host
    go      Run virsh on a kvm host
    view    Run virt-viewer access a kvm virtual
    ssh     Ssh to ssh server'''
    print
    print 'Examples:'
    print '   ', prog, 'ls   <host|virtual>'
    print '   ', prog, 'go   <host|virtual>'
    print '   ', prog, 'view <virtual>'
    print '   ', prog, 'ssh  <host|virtual> <user>'

def show_alias(a_list):
    print 'Supported host or virtual shortcut:'
    al = [a[0] for a in a_list]
    for i in range(0, len(al), 7):
        print al[i : i+7]

def extend_user(u):
    users = { 'r' : 'root', 'u' : 'ubuntu', 'm' : 'mulisu' }
    try:
        return users[u]
    except KeyError:
        print 'Supported user shortcut:'
        print users
        print
        raise

def main():
    alias = Alias(alias_list)

    q = collections.deque(sys.argv)
    prog = os.path.basename(q.popleft())

    try:
        cmd = q.popleft()
        a = q.popleft()
        h = alias[a]['host']
        if cmd == 'ls':
            ls_host(alias[a]['host'], alias[h]['port'], extend_user('u'))
        elif cmd == 'go':
            go_host(alias[a]['host'], alias[h]['port'], extend_user('u'))
        elif cmd == 'view':
            # host doesn't support command 'view'
            if alias[a]['host'] == alias[a]['real']:
                raise IndexError
            view_real(alias[a]['host'], alias[h]['port'], alias[a]['real'], extend_user('u'))
        elif cmd == 'ssh':
            u = q.popleft()
            ssh_target(alias[a]['real'], alias[a]['port'], extend_user(u))
        else:
            raise IndexError
    except IndexError:
        usage(prog)
    except KeyError:
        show_alias(alias_list)
    
if __name__ == '__main__':
    main()
