#!/usr/bin/env python2

import sys
import os
import string
from urlgrabber.grabber import URLGrabber

wallpapers = ["1920-1200-32776",
              "unnamed--054802011f",
              "unnamed--13012e7228",
              "unnamed--18c4e71e82",
              "unnamed--1a8c3506c2",
              "unnamed--21ca4e79b9",
              "unnamed--41ee9a4c76",
              "unnamed--4d1e84bf9c",
              "unnamed--514eaff801",
              "unnamed--62108c2aaa",
              "unnamed--6fad0a221b",
              "unnamed--71e81de7fc",
              "unnamed--76c125a416",
              "unnamed--a3c9db8391",
              "unnamed--a833466bfa",
              "unnamed--abc8251d04",
              "unnamed--c574b23be8",
              "unnamed--d182097033",
              "unnamed--ec40afa9f3",
              "unnamed--f1da805349",
              "unnamed--fa8e4f53ab",
              "Most-Famous-Characters-characters-",]

url_template = "http://jootix.com/download.php?file=http://i.jootix.com/r/%s.jpg&imageName=%s"

if len(sys.argv) < 2:
    sys.exit('Usage: %s resolution' % sys.argv[0])
    
resolution = sys.argv[1]
g = URLGrabber(reget = 'simple')
for w in wallpapers:
    wr = w + '-' + resolution
    url = url_template % (wr, wr)

    if not os.path.exists(wr + '.jpg'):
        local = g.urlgrab(url, filename = wr + '.jpg')
        print local

#-*- python-mode -*-
